#!/bin/sh
if [-n "$1"]; then exit; fi
git add *
echo "\n********add finishing*******\n"
git commit -m $1
echo "\n********commit finishing*******\n"

git push -u origin master
echo "\n********push finishing*******\n"